# Generated by Django 5.1.7 on 2025-03-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_scrollytelling_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('slide_text', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('copete', models.TextField()),
                ('texto', models.TextField()),
                ('imagen_principal', models.ImageField(upload_to='images')),
            ],
        ),
    ]
