# Generated by Django 5.1.7 on 2025-03-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_principal',
            field=models.ImageField(upload_to='images/proyectos'),
        ),
        migrations.CreateModel(
            name='ProyectoImagenArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/proyectos/archivos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.proyecto')),
            ],
        ),
    ]
