# Generated by Django 5.1.7 on 2025-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_tags_proyecto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='artistas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='entes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='es_servicio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='links',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='locacion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='locacion_ampliada',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='marcas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='videos',
            field=models.TextField(default=''),
        ),
    ]
