# Generated by Django 5.1.7 on 2025-03-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_proyecto_anio_proyecto_artistas_proyecto_entes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='orden_portada',
            field=models.IntegerField(default=-1),
        ),
    ]
