# Generated by Django 5.1.7 on 2025-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_proyecto_orden_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='artistas',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='entes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='links',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='locacion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='locacion_ampliada',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='marcas',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='videos',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
