# Generated by Django 5.1.7 on 2025-03-13 22:26

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_proyecto_anio_alter_proyecto_artistas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoimagenarchivo',
            name='imagen',
            field=models.ImageField(upload_to=website.models.get_file_path),
        ),
    ]
