# Generated by Django 5.1.7 on 2025-03-13 22:51

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_proyecto_imagen_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_principal',
            field=models.ImageField(upload_to=website.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='proyectoimagenarchivo',
            name='imagen',
            field=models.ImageField(upload_to=website.models.get_file_path2),
        ),
    ]
