# Generated by Django 5.1.7 on 2025-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_proyecto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
