# Generated by Django 5.1.7 on 2025-03-18 18:03

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_proyecto_ciudad_proyecto_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('copete', models.TextField()),
                ('texto', models.TextField()),
                ('imagen_principal', models.ImageField(upload_to=website.models.get_file_path_nota)),
            ],
        ),
    ]
