# Generated by Django 5.1.7 on 2025-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='orden_portada',
            field=models.IntegerField(default=-1),
        ),
    ]
