# Generated by Django 5.1.7 on 2025-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_nota_orden_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='slide_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='copete',
            field=models.TextField(blank=True, null=True),
        ),
    ]
