# Generated by Django 5.1.7 on 2025-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_nota_slide_text_nota_subtitulo_alter_nota_copete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('json', models.TextField(default='')),
                ('lenguaje', models.CharField(choices=[('ESPAÑOL', 'esp'), ('PORTUGUESE', 'por'), ('ENGLISH', 'eng')], default='ESPAÑOL', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('calle', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=120)),
            ],
        ),
    ]
