# Generated by Django 5.1.7 on 2025-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_direcciones_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloques',
            name='lenguaje',
            field=models.CharField(choices=[('esp', 'ESPAÑOL'), ('por', 'PORTUGUESE'), ('eng', 'ENGLISH')], default='esp', max_length=30),
        ),
    ]
