# Generated by Django 5.1.7 on 2025-04-01 17:26

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alianza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('posicion', models.CharField(max_length=255)),
                ('resume', models.TextField(blank=True, default='', null=True)),
                ('foto', models.ImageField(upload_to=website.models.get_file_path_persona)),
                ('orden_portada', models.IntegerField(default=-1)),
            ],
        ),
    ]
