# Generated by Django 5.1.7 on 2025-04-03 12:49

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_direcciones_geolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='slide_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='NotaImagenArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=website.models.get_file_path_nota2)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nota')),
            ],
        ),
    ]
