# Generated by Django 5.1.7 on 2025-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_nota_slide_text_alter_nota_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
