# Generated by Django 5.1.7 on 2025-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_nota_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='publicar',
            field=models.BooleanField(default=True),
        ),
    ]
