# Generated by Django 5.1.7 on 2025-04-04 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_nota_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='external_autor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='source',
            field=models.CharField(blank=True, default='NOTA ORIGINAL', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NotaAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.nota')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.persona')),
            ],
        ),
    ]
