# Generated by Django 5.1.7 on 2025-04-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_nota_external_autor_nota_source_notaautor'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
    ]
