# Generated by Django 5.1.7 on 2025-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_mensajesdejados'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollytelling',
            name='lenguaje',
            field=models.CharField(choices=[('esp', 'ESPAÑOL'), ('por', 'PORTUGUESE'), ('eng', 'ENGLISH')], default='esp', max_length=30),
        ),
    ]
