# Generated by Django 5.1.7 on 2025-04-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_scrollytelling_lenguaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='name_eng',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='name_por',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
