# Generated by Django 5.1.7 on 2025-04-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_tags_name_eng_tags_name_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='copete_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='copete_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slide_text_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slide_text_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subtitulo_eng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subtitulo_por',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='texto_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='texto_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_eng',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='titulo_por',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
