# Generated by Django 5.1.7 on 2025-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_proyecto_copete_eng_proyecto_copete_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='resume_eng',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='resume_por',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
