# Generated by Django 5.1.7 on 2025-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_persona_resume_eng_persona_resume_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='copete_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='copete_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='slide_text_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='slide_text_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='subtitulo_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='subtitulo_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='texto_eng',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='texto_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='titulo_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='titulo_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
